"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var koa_1 = require("koa");
var cors_1 = require("@koa/cors");
var router_1 = require("@/router");
var koa_bodyparser_1 = require("koa-bodyparser");
var app = new koa_1.default();
app.use((0, cors_1.default)());
app.use((0, koa_bodyparser_1.default)());
app.use(router_1.default.routes());
app.use(router_1.default.allowedMethods());
app.listen(3000);
